Task4
EviLCaT12/Hospital_Back_end pull request #7
Opened 2022-11-18 14:58 UTC by EviLCaT12

Complete task 4

2022-11-18 15:32 UTC, V0D14Ka requested changes

2022-11-18 15:32 UTC, V0D14Ka commented on DataBase/Models/DoctorModel.cs
> +        public Specialization Specialization { get; set; }
почему не specializationModel?

2022-11-18 15:32 UTC, V0D14Ka commented on DataBase/Repository/TimeTableRepo.cs
> +            var _doctor = _context.Doctors.FirstOrDefault(d => d.Id == doctor.Id);
зачем искать доктора когда его уже передал?

2022-11-18 15:32 UTC, V0D14Ka commented on DataBase/Repository/TimeTableRepo.cs
> +            var res = _context.TimeTables.FirstOrDefault(t => t.DoctorId == _doctor.Id && t.date == _timeTable.date);
по дате ищешь таймтейбл и берешь из него ту же самую дату?

2022-11-18 15:32 UTC, V0D14Ka commented on DataBase/Repository/VisitRepo.cs
> +            else return true;
ретерн заменяется одной строчкой, уже так писал в других репах

2022-11-18 15:53 UTC, V0D14Ka approved these changes

2022-11-22 10:38 UTC, Vixorem approved these changes

2022-11-22 14:43 UTC, merged